<?php

use Phalcon\Tag as Tag; ?>

<div class="container">
    <?php $this->elements->getLoginHeader(); ?>
    <?php $this->elements->getNavMenu(); ?>

    <!-- Jumbotron -->
    <div class="jumbotron">
        <h1>Ebook Dungeon</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>
        <p><?php
            echo Phalcon\Tag::linkTo(array("session",
                "Sign up today",
                "class" => "btn btn-lg btn-success"));
            ?>
        </p>
    </div>
</div>