<?php
use Phalcon\Tag;

?>

<?php echo $this->getContent(); ?>

<h1>Share E-books</h1>
<div style="height: 50px;"></div>
<table class="table table-blue table-bordered table-striped" align="center">
    <thead>
    <tr>
        <th>Id</th>
        <th colspan="2">Name</th>
        <th>Type</th>
        <th>Size</th>
        <th>Status</th>
        <th>Created</th>
        <th colspan="2">Uploaded</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $i = 1;
    foreach ($page->items as $content) {
        ?>
        <tr>
            <?php if (in_array($content->content_id, $need_content_ids)) { ?>
            <td><?php echo $content->content_id ?></td>
            <td colspan="2"><?php echo $this->tag->linkTo(array("contents/show/" . $content->content_id, $content->content_name)) ?></td>
            <td><?php echo $content->file_type ?></td>
            <td><?php echo Utils::formatFileSize($content->content_size) ?></td>
            <td>
                <?php
                $status = $content->status;
                if ($status == 'shared')
                    echo "<span class=\"label label-success\">Member Only</span>";
                elseif ($status == 'private')
                    echo "<span class=\"label label-warning\">Only Me</span>";
                else
                    echo "<span class=\"label label-info\">Public</span>";
                ?>
            </td>
            <td><?php echo $content->created ?></td>
            <td colspan="2"><?php echo $content->uploaded ?></td>
            <?php } ?>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
    <tr>
        <td colspan="8" align="right">
            <table align="center">
                <tr>
                    <td><?php echo $this->tag->linkTo(array("contents/index", '<span class="glyphicon glyphicon-fast-backward"></span> First', "role" => "button", "class" => "btn btn-default")) ?></td>
                    <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->before, '<span class="glyphicon glyphicon-chevron-left"></span> Previous', "role" => "button", "class" => "btn btn-default")) ?></td>
                    <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->next, 'Next <span class="glyphicon glyphicon-chevron-right"></span>', "role" => "button", "class" => "btn btn-default")) ?></td>
                    <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->last, 'Last <span class="glyphicon glyphicon-fast-forward"></span>', "role" => "button", "class" => "btn btn-default")) ?></td>
                    <td><?php echo $page->current, "/", $page->total_pages ?></td>
                </tr>
            </table>
        </td>
    </tr>
    <tbody>
</table>