<div class="container">
    <div class="row" id="sign-in-row">
        <div class="col-lg-4">                  
        </div>
        <div class="col-lg-4">
        </div>
        <div class="col-lg-4" id="sign-in">
            <span id="signin-container" class="btn-sm">
                Already a customer, <?php
                echo Phalcon\Tag::linkTo(array("session",
                    "log in",
                    "class" => "btn-sm btn-login"));
                ?> 
            </span>
        </div>
    </div>

<?php $this->elements->getNavMenu(); ?>

    <!-- Jumbotron -->
    <div class="jumbotron">
        <img src="/img/logo.png">
        <br><br>
        <p><?php
echo Phalcon\Tag::linkTo(array("session",
    "Sign up today",
    "class" => "btn btn-lg btn-success"));
?><br><br>
            <img src="/img/reading.jpg" style="width: 70%">
        </p>
    </div>

    <!-- Site footer -->
    <div class="footer">
        <p>&copy; Company 2014</p>
    </div>

</div> <!-- /container -->