<div class="container">
    <div class="row" id="sign-in-row">
        <div class="col-lg-4">                  
        </div>
        <div class="col-lg-4">
        </div>
        <div class="col-lg-4" id="sign-in">
            <span id="signin-container" class="btn-sm">
                Already a customer, <?php
                echo Phalcon\Tag::linkTo(array("session",
                    "log in",
                    "class" => "btn-sm btn-login"));
                ?> 
            </span>
        </div>
    </div>

<?php $this->elements->getNavMenu(); ?>

    <!-- Jumbotron -->
    <div class="jumbotron">
        <h1>Ebook Dungeon</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet.</p>
        <p><?php
echo Phalcon\Tag::linkTo(array("session",
    "Sign up today",
    "class" => "btn btn-lg btn-success"));
?> 
        </p>
    </div>

    <!-- Example row of columns -->
    <div class="row">
        <div class="col-lg-4">
            <h2>Title</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
            <h2>Title</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
            <h2>Title</h2>
            <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
            <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
        </div>
    </div>

    <!-- Site footer -->
    <div class="footer">
        <p>&copy; Company 2014</p>
    </div>

</div> <!-- /container -->