<?php
use Phalcon\Tag as Tag; ?>

<?php echo $this->getContent(); ?>

<script type="text/javascript" src="/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: "textarea",
        theme: "modern",
        plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime media nonbreaking save table contextmenu directionality",
            "emoticons template paste textcolor moxiemanager"
        ],
        toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
        toolbar2: "print preview media | forecolor backcolor emoticons",
        image_advtab: true,
        templates: [
            {title: 'Test template 1', content: 'Test 1'},
            {title: 'Test template 2', content: 'Test 2'}
        ]
    });
</script>

<?php
echo Tag::form(array(
    "id" => "createContentForm",
    "contents/save",
    "method" => "post"
));
?>
    <textarea name="content" style="width:100%"></textarea>
    <br />
    <div style="align">
        <input type="submit" class="btn btn-large btn-success" name="save" value="Submit" />
        <input type="reset" class="btn btn-large" name="reset" value="Reset" />
    </div>
<?php echo Tag::endForm(); ?>