<?php
 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>Your contents</h1>
<table class="table table-blue table-bordered table-striped" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Owner Id</th>
            <th>Type</th>
            <th>Size</th>
            <th>Status</th>
            <th>Created</th>
            <th>Uploaded</th>
            <th colspan="2"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $i = 1;
        foreach ($page->items as $content) {
            ?>
            <tr>
                <td><?php echo $i++ ?></td>
                <td><?php echo $content->content_name ?></td>
                <td><?php echo $content->owner_id ?></td>
                <td><?php echo $content->file_type ?></td>
                <td><?php echo Utils::formatFileSize($content->content_size) ?></td>
                <td><?php echo $content->status ?></td>
                <td><?php echo $content->created ?></td>
                <td><?php echo $content->uploaded ?></td>
                <td class="center-container"><?php echo $this->tag->linkTo(array("contents/edit/" . $content->content_id, "class" => "btn btn-success", '<span class="glyphicon glyphicon-edit"></span> Edit')); ?></td>
                <td class="center-container"><?php echo $this->tag->linkTo(array("contents/delete/" . $content->content_id, "class" => "btn btn-danger", '<span class="glyphicon glyphicon-remove"></span> Delete')); ?></td>
            </tr>
        <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="10" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo(array("contents/index", '<span class="glyphicon glyphicon-fast-backward"></span> First', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->before, '<span class="glyphicon glyphicon-chevron-left"></span> Previous', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->next, 'Next <span class="glyphicon glyphicon-chevron-right"></span>', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->last, 'Last <span class="glyphicon glyphicon-fast-forward"></span>', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>

<!-- blueimp Gallery styles -->
<link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->

<!-- CSS adjustments for browsers with JavaScript disabled -->
<noscript><link rel="stylesheet" href="/upload_plugin/css/jquery.fileupload-noscript.css"></noscript>
<noscript><link rel="stylesheet" href="/upload_plugin/css/jquery.fileupload-ui-noscript.css"></noscript>

<!-- The file upload form used as target for the file upload widget -->
<?php
echo Tag::form(array(
    "id" => "fileupload",
    "contents/upload",
    "method" => "post",
    "enctype" => "multipart/form-data"
));
?>
<!-- Redirect browsers with JavaScript disabled to the origin page -->
<noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>

<!-- The global progress state -->
<div class="row fileupload-buttonbar">
    <div class="col-lg-12 fileupload-progress fade">
        <!-- The global progress bar -->
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
        </div>
        <!-- The extended global progress state -->
        <div class="progress-extended">&nbsp;</div>
    </div>
</div>

<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
<div class="row fileupload-buttonbar">
    <div class="col-lg-12">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>Add files...</span>
            <input type="file" name="files[]" multiple>
        </span>
        <button type="submit" class="btn btn-primary start">
            <i class="glyphicon glyphicon-upload"></i>
            <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
            <i class="glyphicon glyphicon-ban-circle"></i>
            <span>Cancel upload</span>
        </button>

        <!-- The global file processing state -->
        <span class="fileupload-process"></span>
    </div>
    
</div>


<!-- The table listing the files available for upload/download -->
<table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
</form>
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
    <td>
    <span class="preview"></span>
    </td>
    <td>
    <p class="name">{%=file.name%}</p>
    <strong class="error text-danger"></strong>
    </td>
    <td>
    <p class="size">Processing...</p>
    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
    </td>
    <td>
    {% if (!i && !o.options.autoUpload) { %}
    <button class="btn btn-primary start" disabled>
    <i class="glyphicon glyphicon-upload"></i>
    <span>Start</span>
    </button>
    {% } %}
    {% if (!i) { %}
    <button class="btn btn-warning cancel">
    <i class="glyphicon glyphicon-ban-circle"></i>
    <span>Cancel</span>
    </button>
    {% } %}
    </td>
    </tr>
    {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
    <td>
    <span class="preview">
    {% if (file.thumbnailUrl) { %}
    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
    {% } %}
    </span>
    </td>
    <td>
    <p class="name">
    {% if (file.url) { %}
    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
    {% } else { %}
    <span>{%=file.name%}</span>
    {% } %}
    </p>
    {% if (file.error) { %}
    <div><span class="label label-danger">Error</span> {%=file.error%}</div>
    {% } %}
    </td>
    <td>
    <span class="size">{%=o.formatFileSize(file.size)%}</span>
    </td>
    <td>
    {% if (file.deleteUrl) { %}
    <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
    <i class="glyphicon glyphicon-trash"></i>
    <span>Delete</span>
    </button>
    <input type="checkbox" name="delete" value="1" class="toggle">
    {% } else { %}
    <button class="btn btn-warning cancel">
    <i class="glyphicon glyphicon-ban-circle"></i>
    <span>Cancel</span>
    </button>
    {% } %}
    </td>
    </tr>
    {% } %}
</script>