<?php
 use Phalcon\Tag as Tag; ?>

<?php $this->getContent(); ?>
<div class="page-header">
    <h2>Contact Us</h2>
</div>

<div class="row">
    <div class="col-md-6">
        <p>Send us a message and let us know how we can help. Please be as descriptive as possible as it will help us serve you better.</p>

        <?php
        echo Tag::form(array(
            "contactus/send",
            "method" => "post"
        ));
        ?>
        <fieldset>
            <div class="control-group">
                <label class="control-label" for="name">Your Full Name</label>
                <div class="controls">
                    <input type="text" class="form-control" name="name" required>
                    <p class="help-block">(required)</p>
                    <div class="alert">
                        <strong class='warning'>Warning!</strong> Please enter your full name
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="email">Email address</label>
                <div class="controls">
                    <input type="text" name="email" class="form-control" required>
                    <p class="help-block">(required)</p>
                    <div class="alert">
                        <strong class='warning'>Warning!</strong> Please enter your email
                    </div>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="comments">Comments</label>
                <div class="controls">
                    <textarea name="comments" cols="10" rows="5" class="form-control" required></textarea>
                    <p class="help-block">(required)</p>
                    <div class="alert">
                        <strong class='warning'>Warning!</strong> Please enter your email
                    </div>
                </div>
            </div>

            <div class="form-actions">
                <?php
                echo Tag::submitButton(array(
                    "Send",
                    "class" => "btn btn-sm btn-primary",
                    "name" => "send"
                ));
                ?>
            </div>
        </fieldset>
        </form>
    </div>
    <div class="col-md-6">
        <div id="map-canvas"></div>
    </div>
</div>
<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD49KrG7mNpfWwAVz1motJ-jRRo30VbWyA&sensor=false">
    </script>
    <script type="text/javascript">
      function initialize() {
          var latLng = new google.maps.LatLng(21.008611, 105.851608);
        var mapOptions = {
          center: latLng,
          zoom: 8
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);
        
        var marker = new google.maps.Marker({
            position: latLng,
            map: map
        });
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>