<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>Member contents</h1>
<table class="table table-blue table-bordered table-striped" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Member</th>
            <th>Type</th>
            <th>Size</th>
            <th>Created</th>
            <th>Uploaded</th>
         </tr>
    </thead>
    <tbody>
    <?php 
    $i = 1;
    foreach ($page->items as $content) { ?>
        <tr>
            <td><?php echo $i++; ?></td>
            <td><?php echo $this->tag->linkTo(array("contents/show/" . $content->contents->content_id, $content->contents->content_name)) ?></td>
            <td><?php echo $content->user_name ?></td>
            <td><?php echo $content->contents->file_type ?></td>
            <td><?php echo Utils::formatFileSize($content->contents->content_size) ?></td>
            <td><?php echo $content->contents->created ?></td>
            <td><?php echo $content->contents->uploaded ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="10" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo(array("contents/index", '<span class="glyphicon glyphicon-fast-backward"></span> First', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->before, '<span class="glyphicon glyphicon-chevron-left"></span> Previous', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->next, 'Next <span class="glyphicon glyphicon-chevron-right"></span>', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("contents/index?page=" . $page->last, 'Last <span class="glyphicon glyphicon-fast-forward"></span>', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
</table>
