<?php
 use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<h1>Group members</h1>

<p style="text-align: left;"><b>Group Name: </b><span class="label label-warning" style="font-size:1.0em;"><?php echo $groupName->group_name ?></span></p>

<table class="table table-blue table-bordered table-striped" align="center">
    <thead>
        <tr>
            <th style="width: 1%;">Id</th>
            <th>Member</th>
            <th>Shared</th>
            <th>Status</th>
            <th style="width:330px;"></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $i = 1;
        foreach ($page->items as $content) {
            ?>
            <tr>
                <td><?php echo $i++ ?></td>
                <td><?php echo $content->user_name ?></td>
                <td>
                </td>
                <td>
                    <?php
                    $status = $content->groupMember->member_status;

                    if ($status == 'active')
                        echo "<span class=\"label label-success\">$status</span>";
                    elseif ($status == 'pending') {
                        echo "<span class=\"label label-warning\">$status</span>";
                    } elseif ($status == 'rejected') {
                        echo "<span class=\"label label-danger\">$status</span>";
                    }
                    ?>
                </td>

                <td class="center-container">
                    <?php echo $this->tag->linkTo(array("groupadmin/active/" . $content->groupMember->member_id, "class" => "btn btn-default", '<span class="glyphicon glyphicon-plus-sign"></span> Enable')); ?>
                    <?php echo $this->tag->linkTo(array("groupadmin/reject/" . $content->groupMember->member_id, "class" => "btn btn-default", '<span class="glyphicon glyphicon-minus-sign"></span> Disable')); ?>
                    <?php echo $this->tag->linkTo(array("groupadmin/delete/" . $content->groupMember->member_id, "class" => "btn btn-danger", '<span class="glyphicon glyphicon-remove"></span> Delete')); ?>

                </td>
            </tr>
        <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="10" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo(array("groupadmin/index", '<span class="glyphicon glyphicon-fast-backward"></span> First', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("groupadmin/index?page=" . $page->before, '<span class="glyphicon glyphicon-chevron-left"></span> Previous', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("groupadmin/index?page=" . $page->next, 'Next <span class="glyphicon glyphicon-chevron-right"></span>', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $this->tag->linkTo(array("groupadmin/index?page=" . $page->last, 'Last <span class="glyphicon glyphicon-fast-forward"></span>', "role" => "button", "class" => "btn btn-default")) ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>

</table>

<div class="pull-left">
    <?php
    echo Tag::form(array(
        "groupadmin/changegroupname",
        "method" => "post",
        "class" => "form-inline",
    ));
    ?>
    <?php echo Tag::textField(array('group_name', 'placeholder' => 'Enter new group name', 'class' => 'form-control')); ?>
    <?php echo Tag::submitButton(array("Update", 'class' => 'btn btn-sm btn-warning')) ?>

    <?php echo Tag::endForm(); ?>
</div>