<?php

 use Phalcon\Tag as Tag; ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <?php
        echo Tag::getTitle();
        echo Tag::stylesheetLink("css/bootstrap/bootstrap-3.1.1.min.css");
        echo Tag::stylesheetLink("css/bootstrap-dialog.css");
        echo Tag::stylesheetLink("css/justified-nav.css");
        echo Tag::stylesheetLink("css/dashboard.css");
        echo Tag::stylesheetLink("css/style.css");
        ?>
        <?php $this->assets->outputCss() ?>
        
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <?php echo Tag::javascriptInclude('js/jquery-2.1.0.min.js'); ?>
        <?php echo Tag::javascriptInclude('js/utils.js'); ?>
    </head>
    <body>
        <?php echo $this->getContent(); ?>

        <?php echo Tag::javascriptInclude('js/bootstrap/bootstrap.min-3.1.1.js'); ?>
        <?php echo Tag::javascriptInclude('js/jquery.confirm.min.js'); ?>
        <?php echo Tag::javascriptInclude('js/bootstrap-dialog.min.js'); ?>
        <?php echo Tag::javascriptInclude('js/main.js'); ?>
        
        <?php $this->assets->outputJs() ?>
        
    </body>
</html>
